package pmgbot

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestFileConfigRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pmgbot.yaml")
	config := FileConfig{
		LogLevel:  "debug",
		LogPath:   "pmgbot.log",
		Sudo:      true,
		Blacklist: "blacklist.txt",
		Exclude:   "exclude.txt",
		Daemon: FileDaemonConfig{
			Before:          Duration(30 * time.Minute),
			Every:           Duration(15 * time.Minute),
			ParseTimeout:    Duration(time.Minute),
			ImporterWhoName: "Blacklist-pmgbot-autogenerated",
			ImportTimeout:   Duration(2 * time.Minute),
		},
	}

	if err := SaveFileConfig(path, config); err != nil {
		t.Fatal(err)
	}
	loaded, err := LoadFileConfig(path)
	if err != nil {
		t.Fatal(err)
	}

	if loaded.LogLevel != config.LogLevel {
		t.Fatalf("got log level %q, want %q", loaded.LogLevel, config.LogLevel)
	}
	if time.Duration(loaded.Daemon.Every) != 15*time.Minute {
		t.Fatalf("got daemon every %s, want 15m", time.Duration(loaded.Daemon.Every))
	}
	if time.Duration(loaded.Daemon.Before) != 30*time.Minute {
		t.Fatalf("got daemon before %s, want 30m", time.Duration(loaded.Daemon.Before))
	}
	if time.Duration(loaded.Daemon.ImportTimeout) != 2*time.Minute {
		t.Fatalf("got import timeout %s, want 2m", time.Duration(loaded.Daemon.ImportTimeout))
	}
	if loaded.DaemonConfig().Exclude != "exclude.txt" {
		t.Fatalf("got daemon exclude %q, want exclude.txt", loaded.DaemonConfig().Exclude)
	}
}

func TestDurationUnmarshalError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pmgbot.yaml")
	content := strings.Join([]string{
		`log_level: info`,
		`log_path: ""`,
		`sudo: true`,
		`blacklist: blacklist.txt`,
		`exclude: exclude.txt`,
		`daemon:`,
		`  before: 30m`,
		`  every: 15m`,
		`  parse_timeout: nope`,
		`  importer_who_name: Blacklist-pmgbot-autogenerated`,
		`  import_timeout: 1m`,
	}, "\n")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	_, err := LoadFileConfig(path)
	if err == nil {
		t.Fatal("expected duration parse error")
	}
}

func TestDurationSetUsesMinutesForBareNumber(t *testing.T) {
	var duration Duration
	if err := duration.Set("30"); err != nil {
		t.Fatal(err)
	}
	if time.Duration(duration) != 30*time.Minute {
		t.Fatalf("got %s, want 30m", time.Duration(duration))
	}
}

func TestDurationUnmarshalUsesMinutesForBareNumber(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pmgbot.yaml")
	content := strings.Join([]string{
		`log_level: info`,
		`log_path: ""`,
		`sudo: true`,
		`blacklist: blacklist.txt`,
		`exclude: exclude.txt`,
		`daemon:`,
		`  before: 30`,
		`  every: 15m`,
		`  parse_timeout: 1m`,
		`  importer_who_name: Blacklist-pmgbot-autogenerated`,
		`  import_timeout: 1m`,
	}, "\n")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	config, err := LoadFileConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if time.Duration(config.Daemon.Before) != 30*time.Minute {
		t.Fatalf("got daemon before %s, want 30m", time.Duration(config.Daemon.Before))
	}
}
