package pmgbot

import (
	"context"
	"testing"
	"time"
)

func TestDaemonValidatesEvery(t *testing.T) {
	err := Daemon(context.Background(), DaemonConfig{
		Before:          30 * time.Minute,
		Every:           0,
		ParseTimeout:    time.Minute,
		ImporterWhoName: "Blacklist-pmgbot-autogenerated",
		ImportTimeout:   time.Minute,
	})
	if err == nil {
		t.Fatal("expected validation error")
	}
}

func TestDaemonValidatesTimeouts(t *testing.T) {
	err := Daemon(context.Background(), DaemonConfig{
		Before:          30 * time.Minute,
		Every:           time.Minute,
		ParseTimeout:    0,
		ImporterWhoName: "Blacklist-pmgbot-autogenerated",
		ImportTimeout:   time.Minute,
	})
	if err == nil {
		t.Fatal("expected parser timeout validation error")
	}

	err = Daemon(context.Background(), DaemonConfig{
		Before:          30 * time.Minute,
		Every:           time.Minute,
		ParseTimeout:    time.Minute,
		ImporterWhoName: "Blacklist-pmgbot-autogenerated",
		ImportTimeout:   0,
	})
	if err == nil {
		t.Fatal("expected importer timeout validation error")
	}
}

func TestDaemonValidatesImporterWhoName(t *testing.T) {
	err := Daemon(context.Background(), DaemonConfig{
		Before:          30 * time.Minute,
		Every:           time.Minute,
		ParseTimeout:    time.Minute,
		ImporterWhoName: " ",
		ImportTimeout:   time.Minute,
	})
	if err == nil {
		t.Fatal("expected importer who name validation error")
	}
}

func TestDaemonValidatesBefore(t *testing.T) {
	err := Daemon(context.Background(), DaemonConfig{
		Before:          0,
		Every:           time.Minute,
		ParseTimeout:    time.Minute,
		ImporterWhoName: "Blacklist-pmgbot-autogenerated",
		ImportTimeout:   time.Minute,
	})
	if err == nil {
		t.Fatal("expected before validation error")
	}
}
