package pmgbot

import (
	"slices"
	"strings"
	"testing"
)

func TestPMGWhoIDFromOutput(t *testing.T) {
	out := []byte(`200 OK
[
   {
      "id" : 91,
      "info" : "req by GUMVS",
      "name" : "BLOCK_OON"
   },
   {
      "id" : 92,
      "info" : "Auto generated blacklist from deleted spam",
      "name" : "Blacklist-pmgbot-autogenerated"
   }
]`)

	got, err := pmgWhoIDFromOutput(out, "Blacklist-pmgbot-autogenerated")
	if err != nil {
		t.Fatal(err)
	}
	want := 92
	if got != want {
		t.Fatalf("got %d, want %d", got, want)
	}
}

func TestPMGWhoIDFromOutputIgnoresTrailingStatus(t *testing.T) {
	out := []byte(`[
   {
      "id" : 92,
      "name" : "Blacklist-pmgbot-autogenerated"
   }
]
200 OK`)

	got, err := pmgWhoIDFromOutput(out, "Blacklist-pmgbot-autogenerated")
	if err != nil {
		t.Fatal(err)
	}
	if got != 92 {
		t.Fatalf("got %d, want 92", got)
	}
}

func TestPMGWhoIDFromOutputReturnsErrorForMissingName(t *testing.T) {
	out := []byte(`200 OK
[
   {
      "id" : 92,
      "name" : "Blacklist-pmgbot-autogenerated"
   }
]`)

	_, err := pmgWhoIDFromOutput(out, "missing")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestPMGWhoObjectsFromOutput(t *testing.T) {
	out := []byte(`200 OK
[
   {
      "descr" : "admins@gilandroyprops.net",
      "email" : "admins@gilandroyprops.net",
      "id" : 4735,
      "ogroup" : 92,
      "otype" : 1001,
      "otype_text" : "Mail address",
      "receivertest" : 0
   }
]`)

	objects, err := pmgWhoObjectsFromOutput(out)
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 1 {
		t.Fatalf("got %d objects, want 1", len(objects))
	}
	got := objects[0]
	if got.ID != 4735 {
		t.Fatalf("got id %d, want 4735", got.ID)
	}
	if got.OGroup != 92 {
		t.Fatalf("got ogroup %d, want 92", got.OGroup)
	}
	if got.Email != "admins@gilandroyprops.net" {
		t.Fatalf("got email %q, want %q", got.Email, "admins@gilandroyprops.net")
	}
	if got.OTypeText != "Mail address" {
		t.Fatalf("got otype text %q, want %q", got.OTypeText, "Mail address")
	}
}

func TestPMGWhoObjectsFromOutputIgnoresTrailingStatus(t *testing.T) {
	out := []byte(`[
   {
      "email" : "admins@gilandroyprops.net",
      "id" : 4735,
      "ogroup" : 92
   }
]
200 OK`)

	objects, err := pmgWhoObjectsFromOutput(out)
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 1 {
		t.Fatalf("got %d objects, want 1", len(objects))
	}
	if objects[0].Email != "admins@gilandroyprops.net" {
		t.Fatalf("got email %q, want %q", objects[0].Email, "admins@gilandroyprops.net")
	}
}

func TestMissingPMGWhoEmails(t *testing.T) {
	got := missingPMGWhoEmails(
		[]string{"old@example.com", "new@example.com", "NEW@example.com", " next@example.com "},
		[]pmgWhoObject{
			{Email: "OLD@example.com"},
			{Email: ""},
		},
	)
	want := []string{"new@example.com", "next@example.com"}
	if len(got) != len(want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %#v, want %#v", got, want)
		}
	}
}

func TestExcludeEmails(t *testing.T) {
	got, err := excludeEmails(
		[]string{"a@example.com", "B@example.com", " c@example.org ", "keep@example.net", "a@example.com", ""},
		[]string{`^b@example\.com$`, `@example\.org$`, `^B@EXAMPLE\.COM$`},
	)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"a@example.com", "keep@example.net"}
	if !slices.Equal(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestExcludeEmailsDomainWildcardPattern(t *testing.T) {
	got, err := excludeEmails(
		[]string{"user@domain.com", "other@DOMAIN.com", "admin@sub.domain.com", "keep@example.com"},
		[]string{`^[^@]+@domain\.com$`},
	)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"admin@sub.domain.com", "keep@example.com"}
	if !slices.Equal(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestExcludeEmailsFiltersMergedBlacklistSenders(t *testing.T) {
	merged := appendUniqueSenders(
		[]string{"old@domain.com", "keep@example.com"},
		[]string{"new@domain.com", "next@example.com"},
	)
	got, err := excludeEmails(merged, []string{`^[^@]+@domain\.com$`})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"keep@example.com", "next@example.com"}
	if !slices.Equal(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestExcludeEmailsReturnsRegexError(t *testing.T) {
	_, err := excludeEmails([]string{"a@example.com"}, []string{"["})
	if err == nil {
		t.Fatal("expected regexp error")
	}
	if !strings.Contains(err.Error(), "compile exclude pattern") {
		t.Fatalf("got %q, want compile exclude pattern error", err)
	}
}
