package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/charmbracelet/fang"
	"github.com/spf13/cobra"

	"pmgbot/internal/pmgbot"
	pmgcmd "pmgbot/pkg/cmd"
)

const (
	defaultImporterWhoName = "Blacklist-pmgbot-autogenerated"
	defaultImportTimeout   = 10 * time.Minute
	defaultParseTimeout    = 10 * time.Minute
	defaultBefore          = 30 * time.Minute
	defaultDaemonEvery     = 15 * time.Minute
	defaultConfigPath      = "pmgbot.yaml"
	defaultExclude         = "exclude.txt"
	defaultLogLevel        = "info"
)

type cliConfig struct {
	Blacklist  string
	ConfigPath string
	Exclude    string
	LogPath    string
	LogLevel   string
	Sudo       bool
	SaveConfig bool
}

func main() {
	if err := fang.Execute(context.Background(), rootCmd(), fang.WithoutVersion()); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func rootCmd() *cobra.Command {
	var config cliConfig

	root := &cobra.Command{
		Use:           "pmgbot",
		Short:         "Parse and import deleted PMG spam senders",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if config.SaveConfig {
				return saveDefaultConfig(config.ConfigPath)
			}

			return cmd.Help()
		},
		CompletionOptions: cobra.CompletionOptions{
			DisableDefaultCmd: true,
		},
	}
	root.SetHelpCommand(&cobra.Command{Hidden: true})
	root.PersistentFlags().StringVar(
		&config.Blacklist,
		"blacklist",
		"blacklist.txt",
		"path for unique deleted spam senders",
	)
	root.PersistentFlags().StringVar(
		&config.ConfigPath,
		"config",
		defaultConfigPath,
		"path to yaml config for daemon and --save-config",
	)
	root.PersistentFlags().StringVar(
		&config.Exclude,
		"exclude",
		defaultExclude,
		"path for senders to skip during import",
	)
	root.PersistentFlags().StringVar(
		&config.LogPath,
		"log-path",
		"",
		"path to log file",
	)
	root.PersistentFlags().StringVar(
		&config.LogLevel,
		"log-level",
		defaultLogLevel,
		"log level: debug|info|warn|error",
	)
	root.PersistentFlags().BoolVar(
		&config.Sudo,
		"sudo",
		true,
		"run external commands through sudo",
	)
	root.PersistentFlags().BoolVar(
		&config.SaveConfig,
		"save-config",
		false,
		"save default yaml config and exit",
	)

	root.AddCommand(parseCmd(&config))
	root.AddCommand(importCmd(&config))
	root.AddCommand(daemonCmd(&config))

	return root
}

func parseCmd(logConfig *cliConfig) *cobra.Command {
	var config pmgbot.ParserConfig

	parse := &cobra.Command{
		Use:           "parse",
		Short:         "Collect senders from deleted PMG spam messages",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			if logConfig.SaveConfig {
				return saveDefaultConfig(logConfig.ConfigPath)
			}

			config.Blacklist = logConfig.Blacklist
			pmgcmd.SetSudo(logConfig.Sudo)

			if err := configureLogger(logConfig.LogLevel, logConfig.LogPath); err != nil {
				return err
			}

			if err := pmgbot.Parse(config); err != nil {
				slog.Error("pmgbot parse failed", "error", err)
				return err
			}

			return nil
		},
	}

	before := pmgbot.Duration(defaultBefore)
	parse.Flags().Var(
		&before,
		"before",
		"look back interval for journalctl; bare numbers are minutes",
	)
	parse.Flags().DurationVar(
		&config.Timeout,
		"timeout",
		defaultParseTimeout,
		"parse operation timeout",
	)
	parse.PreRunE = func(_ *cobra.Command, _ []string) error {
		config.Before = time.Duration(before)
		return nil
	}

	return parse
}

func importCmd(logConfig *cliConfig) *cobra.Command {
	var config pmgbot.ImporterConfig

	importer := &cobra.Command{
		Use:           "import",
		Short:         "Find PMG who object id for import target",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			if logConfig.SaveConfig {
				return saveDefaultConfig(logConfig.ConfigPath)
			}

			config.Blacklist = logConfig.Blacklist
			config.Exclude = logConfig.Exclude
			pmgcmd.SetSudo(logConfig.Sudo)

			if err := configureLogger(logConfig.LogLevel, logConfig.LogPath); err != nil {
				return err
			}

			id, err := pmgbot.Import(config)
			if err != nil {
				slog.Error("pmgbot import failed", "error", err)
				return err
			}
			fmt.Println(id)

			return nil
		},
	}
	importer.Flags().StringVar(
		&config.WhoName,
		"name",
		defaultImporterWhoName,
		"PMG who object name",
	)
	importer.Flags().DurationVar(
		&config.Timeout,
		"timeout",
		defaultImportTimeout,
		"import operation timeout",
	)

	return importer
}

func daemonCmd(logConfig *cliConfig) *cobra.Command {
	daemon := &cobra.Command{
		Use:           "daemon",
		Short:         "Periodically parse and import deleted PMG spam senders",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if logConfig.SaveConfig {
				return saveDefaultConfig(logConfig.ConfigPath)
			}

			fileConfig, err := pmgbot.LoadFileConfig(logConfig.ConfigPath)
			if err != nil {
				return err
			}
			pmgcmd.SetSudo(fileConfig.Sudo)

			if err := configureLogger(fileConfig.LogLevel, fileConfig.LogPath); err != nil {
				return err
			}

			if err := pmgbot.Daemon(cmd.Context(), fileConfig.DaemonConfig()); err != nil {
				slog.Error("pmgbot daemon failed", "error", err)
				return err
			}

			return nil
		},
	}

	return daemon
}

func defaultFileConfig(_ time.Time) pmgbot.FileConfig {
	return pmgbot.FileConfig{
		LogLevel:  defaultLogLevel,
		LogPath:   "",
		Sudo:      true,
		Blacklist: "blacklist.txt",
		Exclude:   defaultExclude,
		Daemon: pmgbot.FileDaemonConfig{
			Before:          pmgbot.Duration(defaultBefore),
			Every:           pmgbot.Duration(defaultDaemonEvery),
			ParseTimeout:    pmgbot.Duration(defaultParseTimeout),
			ImporterWhoName: defaultImporterWhoName,
			ImportTimeout:   pmgbot.Duration(defaultImportTimeout),
		},
	}
}

func saveDefaultConfig(path string) error {
	if err := pmgbot.SaveFileConfig(path, defaultFileConfig(time.Now())); err != nil {
		return err
	}

	fmt.Fprintf(os.Stdout, "saved config to %s\n", path)
	return nil
}

func configureLogger(levelText, logPath string) error {
	var parsedLevel slog.Level
	if err := parsedLevel.UnmarshalText([]byte(levelText)); err != nil {
		return fmt.Errorf("invalid log level %q: %w", levelText, err)
	}

	h := []slog.Handler{
		slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
			AddSource: true,
			Level:     parsedLevel,
		}),
	}

	if logPath != "" {
		if err := os.MkdirAll(filepath.Dir(logPath), 0o755); err != nil {
			return fmt.Errorf("failed to create log dir for %q: %w", logPath, err)
		}

		logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
		if err != nil {
			return fmt.Errorf("failed to open log file %q: %w", logPath, err)
		}

		h = append(h,
			slog.NewJSONHandler(logFile, &slog.HandlerOptions{
				AddSource: true,
				Level:     parsedLevel,
			}),
		)
	}

	slog.SetDefault(slog.New(slog.NewMultiHandler(h...)))

	return nil
}
